/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlyvattu;

import java.util.List;
import java.util.Stack;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author colan
 */
public class FrameQLVT extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrameQLVT.class.getName());
    AppFunction appFunction;
    
    
    /**
     * Creates new form frameQLVT
     */
    DefaultTableModel defaultTableModel;
    private void setData(List<VatTu> vattus){ 
        for (VatTu vattu : vattus){
            defaultTableModel.addRow(new Object[]{vattu.getId(),
                vattu.getName(), vattu.getAmount(), vattu.getUnit(),
                vattu.getCategory() });
        }
    }
    public FrameQLVT() {
        initComponents();
        
        //Do du lieu tu CSDL vao bang JTable
        appFunction = new AppFunction();
        defaultTableModel = new DefaultTableModel(){
            //Tat chuc nang sua truc tiep trong bang
            @Override
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        vattuTable.setModel(defaultTableModel);
        defaultTableModel.addColumn("Mã vật tư");
        defaultTableModel.addColumn("Tên vật tư");
        defaultTableModel.addColumn("Số lượng");
        defaultTableModel.addColumn("Đơn vị");
        defaultTableModel.addColumn("Loại");
        List<VatTu> vattus;
        vattus = appFunction.getAllVatTu();
        setData(vattus);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        vattuTable = new javax.swing.JTable();
        refreshButton = new javax.swing.JButton();
        delButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        undoButton = new javax.swing.JButton();
        redoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addButton.setText("Thêm mới");
        addButton.setToolTipText("Thêm vật tư mới");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        vattuTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        vattuTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        vattuTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(vattuTable);

        refreshButton.setIcon(new javax.swing.ImageIcon("E:\\Downloads\\icons8-refresh-30 (1).png")); // NOI18N
        refreshButton.setToolTipText("Làm mới bảng");
        refreshButton.setMaximumSize(new java.awt.Dimension(36, 36));
        refreshButton.setMinimumSize(new java.awt.Dimension(36, 36));
        refreshButton.setPreferredSize(new java.awt.Dimension(40, 40));
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        delButton.setText("Xóa");
        delButton.setToolTipText("Xóa vật tư");
        delButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Sửa");
        updateButton.setToolTipText("Sửa vật tư");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        resetButton.setIcon(new javax.swing.ImageIcon("E:\\Downloads\\icons8-close-48.png")); // NOI18N
        resetButton.setToolTipText("Đóng bảng");
        resetButton.setMaximumSize(new java.awt.Dimension(36, 36));
        resetButton.setMinimumSize(new java.awt.Dimension(36, 36));
        resetButton.setPreferredSize(new java.awt.Dimension(40, 40));
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        undoButton.setText("Undo");
        undoButton.setToolTipText("");
        undoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoButtonActionPerformed(evt);
            }
        });

        redoButton.setText("Redo");
        redoButton.setToolTipText("");
        redoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(addButton)
                        .addGap(18, 18, 18)
                        .addComponent(delButton)
                        .addGap(18, 18, 18)
                        .addComponent(updateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(undoButton)
                        .addGap(18, 18, 18)
                        .addComponent(redoButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(resetButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(refreshButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(delButton)
                    .addComponent(updateButton)
                    .addComponent(undoButton)
                    .addComponent(redoButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        AddVattuFrame addVattuFrame = new AddVattuFrame();
        addVattuFrame.setVisible(true);
    }//GEN-LAST:event_addButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        defaultTableModel.setNumRows(0);
        List<VatTu> vattus;
        vattus = appFunction.getAllVatTu();
        setData(vattus);
        
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void delButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delButtonActionPerformed
        // TODO add your handling code here:
        int row = vattuTable.getSelectedRow();
        //Neu nguoi dung khong chon hang
        if (row == -1){
            JOptionPane.showMessageDialog(rootPane, "Ban phai chon mot hang de xoa!");
        }
        else{
            int confirm = JOptionPane.showConfirmDialog(rootPane, "Ban co chac muon xoa hang nay?");
            if (confirm == JOptionPane.YES_OPTION){
                String id = vattuTable.getValueAt(row, 0).toString();
                appFunction = new AppFunction();
                
                //Them action Del vao Stack                
                Action action = new Action("Del",appFunction.getVattuById(id),null);
                Action.undoStack.push(action);
                
                appFunction.delVatTu(id);
                defaultTableModel.setNumRows(0);
                List<VatTu> vattus;
                vattus = appFunction.getAllVatTu();
                setData(vattus);
                
            }
            
        }
    }//GEN-LAST:event_delButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        int row = vattuTable.getSelectedRow();
        //Neu nguoi dung khong chon hang
        if (row == -1){
            JOptionPane.showMessageDialog(rootPane, "Ban phai chon mot hang de sua!");
        }
        else{
            VatTu vattu = new VatTu();
            vattu.setId(vattuTable.getValueAt(row,0).toString());
            vattu.setName(vattuTable.getValueAt(row,1).toString());
            vattu.setAmount(Integer.parseInt(String.valueOf(vattuTable.getValueAt(row,2))));
            vattu.setUnit(vattuTable.getValueAt(row,3).toString());
            vattu.setCategory(vattuTable.getValueAt(row,4).toString());
            this.dispose();
            
            new UpdateVattuFrame(vattu).setVisible(true);
            
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        vattuTable.setModel(defaultTableModel);
        defaultTableModel.setNumRows(0);
        appFunction = new AppFunction();
        appFunction.closeVattu();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void undoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoButtonActionPerformed
        // TODO add your handling code here:
        appFunction = new AppFunction();
        appFunction.undo();
        
        defaultTableModel.setNumRows(0);
        List<VatTu> vattus;
        vattus = appFunction.getAllVatTu();
        setData(vattus);
        
        
    }//GEN-LAST:event_undoButtonActionPerformed

    private void redoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redoButtonActionPerformed
        // TODO add your handling code here:
        appFunction = new AppFunction();
        appFunction.redo();
        
        defaultTableModel.setNumRows(0);
        List<VatTu> vattus;
        vattus = appFunction.getAllVatTu();
        setData(vattus);
    }//GEN-LAST:event_redoButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */        
        java.awt.EventQueue.invokeLater(() -> new FrameQLVT().setVisible(true));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton delButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton redoButton;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton undoButton;
    private javax.swing.JButton updateButton;
    private javax.swing.JTable vattuTable;
    // End of variables declaration//GEN-END:variables
}
